###########################################################################
# Helm chart values for the first deployment that generates a configuration
###########################################################################
replicaCount: 2

image:
  repository: curity.azurecr.io/curity/idsvr
  tag: latest

curity:
  adminUiHttp: true
  admin:
    serviceAccount:
      name: curity-idsvr-admin
    logging:
      level: INFO

  runtime:
    serviceAccount:
      name: curity-idsvr-runtime
    logging:
      level: INFO

  config:
    uiEnabled: true

networkpolicy:
  enabled: false
