# Default values for curity.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: custom_idsvr
  tag: 7.4.2
  pullPolicy: Never
  pullSecret:

nameOverride: ""
fullnameOverride: ""
labels: {}
networkpolicy:
  enabled: true

curity:
  healthCheckPort: 4465
  adminUiPort: 6749
  adminUiHttp: false

  admin:
    role: admin
    annotations: {}
    service:
      type: ClusterIP
      port: 6789
      annotations: {}
    livenessProbe:
      timeoutSeconds: 1
      failureThreshold: 3
      periodSeconds: 10
      initialDelaySeconds: 120
    readinessProbe:
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 3
      periodSeconds: 10
      initialDelaySeconds: 120
# extraEnv provides additional environment variables
#    extraEnv:
#      - name: SOME_EXTRA_VARIABLE
#        value: "extra-variable-value"
#      - name: SOME_OTHER_EXTRA_VARIABLE_USING_VALUE_FROM
#        valueFrom:
#          fieldRef:
#            fieldPath: status.hostIP
    extraEnv: []

    logging:
      level: INFO
      image: "busybox:latest"
      stdout: false
      logs: []
#        - audit
#        - request
#        - cluster
#        - confsvc
#        - confsvc-internal
#        - post-commit-scripts


  runtime:
    role: default
    annotations: {}
    service:
      type: ClusterIP
      port: 8443
      annotations: {}
    serviceAccount:
      name:
    deployment:
      port: 8443
    livenessProbe:
      timeoutSeconds: 1
      failureThreshold: 3
      periodSeconds: 10
      initialDelaySeconds: 120
    readinessProbe:
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 3
      periodSeconds: 10
      initialDelaySeconds: 120
# extraEnv provides additional environment variables
#    extraEnv:
#      - name: SOME_EXTRA_VARIABLE
#        value: "extra-variable-value"
#      - name: SOME_OTHER_EXTRA_VARIABLE_USING_VALUE_FROM
#        valueFrom:
#          fieldRef:
#            fieldPath: status.hostIP
    extraEnv: []
    logging:
      level: INFO
      image: "busybox:latest"
      stdout: false
      logs: []
#        - audit
#        - request
#        - cluster
#        - confsvc
#        - confsvc-internal
#        - post-commit-scripts

  config:
    uiEnabled: true
    backup: false
    password: Password1
    skipInstall: false
    encryptionKey:
    environmentVariableSecrets: []
    environmentVariableConfigMaps: []
    configuration:
     - configMapRef:
         name: idsvr-configmap
         items:
           - key: main-config
             path: idsvr-config-backup.xml
#      - secretRef:
#          name: cfg-secret
#          items:
#            - key: scrt-1
#              path: scrt-1.xml
#            - key: scrt-2
#              path: scrt-2.xml
#      - secretRef:
#          name: cfg-secret-2
#          items:
#            - key: cfg
#              path: configuration.xml
    convertKeystore: []
#      - sourceTls:
#          keyName: SSL_SERVER_KEY
#          fromSecretRef: curity-local-tls
#          cert: SSL_SERVER_CERT # optional
#          inAlias: curity
#          keystorePasswordSecretRef:
#            name: curity-idsvr-secret
#            key: KEYSTORE_PASSWORD

# Expose the Curity Identity Server using HTTPS and port 443
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  runtime:
    host: login.curity.local
    secretName: curity-local-tls
  admin:
    host: admin.curity.local
    secretName: curity-local-tls

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  customMetrics: []
#    - type: External
#      external:
#        metric:
#          name: idsvr_http_server_request_rate
#        target:
#          type: Value
#          value: 100m

nodeSelector: {}

tolerations: []

affinity: { }
