# 
# A minimal Helm chart for the example deployment
#

replicaCount: 2

image:
  repository: custom_idsvr
  tag: latest
  pullPolicy: Never
  pullSecret:

curity:
  admin:
    logging:
      level: INFO
  
  runtime:
    logging:
      level: INFO

  config:
    uiEnabled: true
    password: Password1
    configuration:
    - configMapRef:
        name: idsvr-configmap
        items:
        - key: main-config
          path: idsvr-config-backup.xml

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  runtime:
    enabled: true
    host: login.curity.local
    secretName: curity-local-tls
  admin:
    enabled: true
    host: admin.curity.local
    secretName: curity-local-tls
