###########################################################################################################
# Ingress routes for the example SPA and API, some of which use plugins.
# Requests from the SPA use the CORS plugin, then the OAuth Proxy plugin and then the Phantom Token plugin.
###########################################################################################################
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webhost-route
spec:
  parentRefs:
  - name: kong-gateway
    namespace: apigateway
  hostnames:
  - www.demoapp.example
  rules:
  - matches:
    - path:
        value: /
    backendRefs:
    - name: webhost-svc
      kind: Service
      port: 8000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demoapi-route
  annotations:
    konghq.com/plugins: cors,oauth-proxy,phantom-token
spec:
  parentRefs:
  - name: kong-gateway
    namespace: apigateway
  hostnames:
  - api.demoapp.example
  rules:
  - matches:
    - path:
        value: /api
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: demoapi-svc
      kind: Service
      port: 8000
