######################################################################################################
# Helm chart values for the redeployments of the Curity Identity Server with an existing configuration
# - The base configuration is that for a default installation
# - The DevOps dashboard configuration contains additional settings to enable that feature
######################################################################################################
replicaCount: 2

image:
  repository: curity.azurecr.io/curity/idsvr
  tag: latest

curity:
  adminUiHttp: true
  admin:
    serviceAccount:
      name: curity-idsvr-admin
    logging:
      level: INFO

  runtime:
    serviceAccount:
      name: curity-idsvr-runtime
    logging:
      level: INFO

  config:
    uiEnabled: true
    skipInstall: true
    configuration:
    - configMapRef:
        name: idsvr-config
        items:
        - key: base-configuration
          path: base-configuration.xml
        - key: devops-dashboard
          path: devops-dashboard.xml
        - key: oauth-clients
          path: oauth-clients.xml
    environmentVariableConfigMaps:
    - idsvr-parameters
    environmentVariableSecrets:
    - idsvr-protected-parameters

networkpolicy:
  enabled: false
