#
# A basic Kubernetes deployment file for PostgreSQL that avoids persistent storage for simplicity
# For demo purposes we also expose the service via port 30432
#

kind: Service
apiVersion: v1
metadata:
  name: postgres-svc
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
      nodePort: 30432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.3
          volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: init-script
            readOnly: true
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Password1
            - name: POSTGRES_DB
              value: idsvr
          ports:
            - containerPort: 5432
              name: postgres
      volumes:
        - name: init-script
          configMap:
            name: init-script-configmap
